# Generated by Django 5.1.5 on 2025-07-14 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('category', '0001_initial'),
        ('segment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('has_5g', models.BooleanField(default=False)),
                ('has_nfc', models.BooleanField(default=False)),
                ('has_water_resistance', models.BooleanField(default=False)),
                ('has_stereo_speakers', models.BooleanField(default=False)),
                ('features_image', models.ImageField(blank=True, null=True, upload_to='phone/features/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segment.segment')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='phone/gallery/')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='phone.phone')),
            ],
        ),
        migrations.CreateModel(
            name='CameraSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='phone/camera_samples/')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_samples', to='phone.phone')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('Network', 'Network'), ('Launch', 'Launch'), ('Body', 'Body'), ('Display', 'Display'), ('Platform', 'Platform'), ('Memory', 'Memory'), ('Main Camera', 'Main Camera'), ('Selfie Camera', 'Selfie Camera'), ('Sound', 'Sound'), ('Comms', 'Comms'), ('Features', 'Features'), ('Battery', 'Battery'), ('Misc', 'Misc'), ('Tests', 'Tests')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='phone.phone')),
            ],
        ),
        migrations.CreateModel(
            name='PriceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('price_npr', models.PositiveIntegerField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_variants', to='phone.phone')),
            ],
        ),
    ]
