# Generated by Django 5.1.5 on 2025-07-14 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneSpecSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('Network', 'Network'), ('Launch', 'Launch'), ('Body', 'Body'), ('Display', 'Display'), ('Platform', 'Platform'), ('Memory', 'Memory'), ('Main Camera', 'Main Camera'), ('Selfie Camera', 'Selfie Camera'), ('Sound', 'Sound'), ('Comms', 'Comms'), ('Features', 'Features'), ('Battery', 'Battery'), ('Misc', 'Misc'), ('Tests', 'Tests')], max_length=50)),
                ('details', models.JSONField(blank=True, default=list)),
                ('value_file', models.FileField(blank=True, null=True, upload_to='phone/spec_files/')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_sections', to='phone.phone')),
            ],
        ),
        migrations.DeleteModel(
            name='PhoneSpec',
        ),
    ]
