# Generated by Django 5.1.5 on 2025-07-14 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_phonespecitem_delete_phonespecsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneSpecSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('Network', 'Network'), ('Launch', 'Launch'), ('Body', 'Body'), ('Display', 'Display'), ('Platform', 'Platform'), ('Memory', 'Memory'), ('Main Camera', 'Main Camera'), ('Selfie Camera', 'Selfie Camera'), ('Sound', 'Sound'), ('Comms', 'Comms'), ('Features', 'Features'), ('Battery', 'Battery'), ('Misc', 'Misc'), ('Tests', 'Tests')], max_length=50)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_sections', to='phone.phone')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneSpecTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='phone.phonespecsection')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneSpecValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='phone.phonespectitle')),
            ],
        ),
        migrations.DeleteModel(
            name='PhoneSpecItem',
        ),
    ]
