# Generated by Django 5.1.5 on 2025-07-14 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0004_phonespecsection_phonespectitle_phonespecvalue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonespecvalue',
            name='title',
        ),
        migrations.RemoveField(
            model_name='phonespecsection',
            name='section',
        ),
        migrations.AddField(
            model_name='phonespecsection',
            name='section_name',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='phonespecsection',
            name='section_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PhoneSpecDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='phone.phonespecsection')),
            ],
        ),
        migrations.DeleteModel(
            name='PhoneSpecTitle',
        ),
        migrations.DeleteModel(
            name='PhoneSpecValue',
        ),
    ]
