# Generated by Django 5.1.5 on 2025-07-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0005_remove_phonespecvalue_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonespecdetail',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
