# Generated by Django 5.1.5 on 2025-07-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0007_remove_phonespecsection_section_title_phonespectitle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camerasample',
            options={'verbose_name_plural': 'Camera Samples'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='phonespecsection',
            options={'verbose_name_plural': 'Phone Spec Sections'},
        ),
        migrations.AlterModelOptions(
            name='phonespectitle',
            options={'verbose_name_plural': 'Titles'},
        ),
        migrations.AlterModelOptions(
            name='phonespecvalue',
            options={'verbose_name_plural': 'Values'},
        ),
        migrations.AlterModelOptions(
            name='pricevariant',
            options={'verbose_name_plural': 'Price Variants'},
        ),
    ]
