# Generated by Django 5.1.5 on 2025-07-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0008_alter_camerasample_options_and_more'),
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='has_nfc',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='has_stereo_speakers',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='has_water_resistance',
        ),
        migrations.AddField(
            model_name='phone',
            name='battery_title',
            field=models.CharField(default='Battery', max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='battery_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='camera_title',
            field=models.CharField(default='Camera', max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='camera_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='display_title',
            field=models.CharField(default='Display', max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='display_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='fiveg_title',
            field=models.CharField(default='5G', max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='memory_title',
            field=models.CharField(default='Memory', max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='memory_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='processor_title',
            field=models.CharField(default='Processor', max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='processor_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='phones', to='type.type'),
        ),
    ]
