# Generated by Django 5.1.5 on 2025-07-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0009_remove_phone_has_nfc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='buy_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
