version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"  # use 5433 on host to avoid conflict

  web:
    build: .
    command: gunicorn HamroMobile.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8002:8000"  # use 8002 on host to avoid conflict
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
