# Generated by Django 5.1.5 on 2025-07-14 06:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsection',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
